language: swift
osx_image: xcode14
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -project UIComponentLibrary.xcodeproj -scheme UIComponentLibrary -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=13.1,name=iPad Pro (9.7-inch)" ONLY_ACTIVE_ARCH=YES
- pod lib lint
